### ISSUE TITLE
CheckoutFormOrder Template Does Not Exist

### ISSUE THREAD

**Issue by gordonbanderson** [swipestripe/silverstripe-swipestripe-coupon#3]
After fixing the control tags I then get an error indicating that the file CheckoutFormOrder.ss cannot be found in my theme.  It is included from OrderForm.ss

```
./swipestripe-coupon/templates/Includes/OrderForm.ss:56:            <% include CheckoutFormOrder %>
```

**Comment by frankmullenger** [comment]
Hi @gordonbanderson, thanks for spotting this. Hopefully the commit above fixes this for you.
