### ISSUE TITLE
Problem with adding coupon code from Order object.

### ISSUE THREAD

**Issue by jason-zz** [swipestripe/silverstripe-swipestripe-coupon#5]
Hi,

I have trouble with the $order->updateModifications() function. After doing couple debugs, I found the problem.

In https://github.com/frankmullenger/silverstripe-swipestripe/blob/2.1/code/order/Order.php#L717

$order calls the modification class like $modification->add($this, $value);

But in https://github.com/frankmullenger/silverstripe-swipestripe-coupon/blob/2.1/code/CouponModification.php#L17

when the modification object try to add the coupon into order, it gets Code data from '$order->CouponCode' instead of '$value'.

So every time the order got updated, all coupon modification data will be gone because it  can't find the correct coupon code.

I hope this makes sense.

**Comment by frankmullenger** [comment]
@irxjason thanks for reporting this! Looks like a bug, would welcome a pull request :smile:. Looks like $order->CouponCode should change to $value?

**Comment by jason-zz** [comment]
@frankmullenger Yeah. I will submit a pull request later. BTW, the swipestripe modules are awesome !

**Comment by frankmullenger** [comment]
@irxjason cheers, and thanks for the pull request, merged!
